import {
  EVENT_STATUSES as ES,
  EVENT_ORIGINS as EO,
} from "@/mixins/globals";

const commonFields = [
  "id",
  "originator",
  "event_origin",
  "status",
  "added_date",
  "files",
];

export const eventsParameters = {
  crteCats: {
    NC: "No conformidad",
    IC: "Incidente",
    OT: "Otro",
    NA: "No aplica",
  },

  statuses: {
    [ES.OPEN]: {
      name: "Pendiente de carga",
      abb: "Pendiente de carga",
      color: "black",
    },
    [ES.PENDING_ACTIONS]: {
      name: "Con acciones pendientes",
      abb: "Acc. Pendientes",
      color: "orange",
    },
    [ES.PENDING_EFFECTIVENESS]: {
      name: "Con acciones para efectivizar",
      abb: "Ac. para efectivizar",
      color: "#449CC9",
    },
    [ES.CERTIFICATE]: {
      name: "Eventos a certificar",
      abb: "Cert. Pendiente",
      color: "#44CC7B",
    },
    [ES.CLOSE]: {
      name: "Cerrado",
      abb: "Cerrado",
      color: "#602424",
    },
  },

  eventOrigins: {
    [EO.CRITICAL_EVENT]: {
      abbr: "EC",
      name: "Evento Crítico",
      description: "",
      img: "EC.svg",
      fca: "CA",
      availableFields: [
        ...commonFields,
        "process_areas",
        "facility",
        "sector",
        "leader",
        "occurrence_date",
        "occurrence_time",
        "summary",
        "description",
        "participants",
        "equipment_category",
        "equipment_description",
        "equipment_id",
        "causes",
        "action_type",
        "classification",
      ],
    },
    [EO.EXTERNAL_AUD]: {
      abbr: "AE",
      name: "Auditoría externa",
      description: "",
      img: "AE.svg",
      fca: "FCA",
      availableFields: [
        ...commonFields,
        "process_areas",
        "facility",
        "leader",
        "occurrence_date",
        "summary",
        "description",
        "findings",
        "action_type",
        "action_cause",
      ],
    },
    [EO.INTERNAL_AUD]: {
      abbr: "AI",
      name: "Auditoría interna",
      description: "",
      img: "AI.svg",
      fca: "FCA",
      availableFields: [
        ...commonFields,
        "process_areas",
        "facility",
        "leader",
        "occurrence_date",
        "summary",
        "description",
        "findings",
        "action_type",
        "action_cause",
      ],
    },
    [EO.MEET]: {
      abbr: "RE",
      name: "Reunión/Otros procesos",
      description: "",
      img: "ME.svg",
      fca: "A",
      availableFields: [
        ...commonFields,
        "process_areas",
        "facility",
        "sector",
        "occurrence_date",
        "leader",
        "summary",
        "description",
        "participants",
        "actions",
      ],
    },
    [EO.CHANGE]: {
      abbr: "GC",
      name: "Gestión de cambio",
      description: "",
      img: "GC.svg",
      fca: "A",
      availableFields: [
        ...commonFields,
        "process_areas",
        "facility",
        "sector",
        "leader",
        "summary",
        "actions",
      ],
    },
    [EO.PROJECT]: {
      abbr: "PR",
      name: "Proyecto",
      description: "",
      img: "PY.svg",
      fca: "A",
      availableFields: [
        ...commonFields,
        "process_areas",
        "facility",
        "sector",
        "summary",
        "actions",
        "action_cause",
      ],
    },
    [EO.OBSERVATION]: {
      abbr: "OB",
      name: "Observación",
      description: "",
      img: "OBS.svg",
      fca: "FCA",
      availableFields: [
        ...commonFields,
        "process_areas",
        "facility",
        "sector",
        "occurrence_date",
        "occurrence_time",
        "findings",
        "actions",
      ],
    },
    [EO.INTERNAL_REQ]: {
      abbr: "RI",
      name: "Requerimiento interno",
      description: "",
      img: "RI.svg",
      fca: "A",
      availableFields: [
        ...commonFields,
        "facility",
        "summary",
        "description",
        "actions",
      ],
    },
    [EO.EXTERNAL_REQ]: {
      abbr: "RL",
      name: "Requerimiento Legal",
      description: "",
      img: "RL.svg",
      fca: "A",
      availableFields: [
        ...commonFields,
        "facility",
        "summary",
        "description",
        "actions",
      ],
    },
  },
};
